### PR TITLE
[debug] Fix hook snapshot command for nested hook paths

### LINKED ISSUE #727: Hook snapshot command did not work correctly for hooks with nested paths
**Expected behavior (what you expected to happen)**:

I have a hook located in the folder `/hooks/100-test/test.sh`. I am execute the command `/shell-operator hook snapshot 100-test/test.sh` and get information about resources

**Actual behavior (what actually happened)**:

 I get a `404 page not found` response

**Steps to reproduce**:
 
1. Start shell-operator with hook in folder `/hooks/100-test/test.sh`
2. Execute command `/shell-operator hook snapshot 100-test/test.sh`

**Environment**:
- 
- Shell-operator version: 1.5.3
- Kubernetes version: 1.28.13
- Installation type (kubectl apply, helm chart, etc.): helm chart

**Anything else we should know?**:

The issue is caused by the fact that the request URL when executing the snapshot command matches the route [registered](https://github.com/flant/shell-operator/blob/a09a79df811f4de1ebfe37a061be3da50795e7fb/pkg/shell-operator/debug_server.go#L56) in the debug server only if there is no nesting in the URL.

In other words, if the hook is located in the `/hooks/test.sh`, the command `/shell-operator hook snapshot test.sh` will execute successfully.

Unfortunately, chi, which is used as the router, only [processes data up to the next “/”](https://github.com/go-chi/chi/issues/988) in the URL, even if we use a regexp like `.*`. Therefore, I don’t know yet how to register a route when the depth of the hook file’s nesting is unknown.

### PR DESCRIPTION
**Pull request by riptide-01**
#### Overview
This PR resolves an issue where the shell-operator hook snapshot command did not work correctly for hooks located in nested directory paths.

#### What this PR does / why we need it
Closes #727 

Changes made:
- Fixed `hook snapshot` command to properly handle nested hook paths
- Fixed CI warnings related to deprecated Ubuntu 20.04 image
- Fixed a bug where the shell-operator server started automatically without `/shell-operator start` command due to unwrapped start.go start function body in return.

##### Output of 
```bash
/shell-operator hook snapshot 100-test/test.sh -o yaml
```
Before:
```bash
404 page not found
```

After:
```yaml
kubernetes:
  operations:
    sinceLastExecution:
      count: 0
      added: 0
      deleted: 6
      modified: 12
      cleaned: 0
    sinceStart:
      count: 4
...
```

Command `/shell-operator/ hook list` works as before
```
["nested_folder/nested_hook.sh","root_hook.sh"]
```

#### Special notes for your reviewer
- [x] Changes were tested in the Kubernetes cluster manually.

### CODE REVIEW

File: pkg/debug/server.go [hunk 1]
```diff
@@ -114,13 +116,19 @@ func (s *Server) RegisterHandler(method, pattern string, handler func(request *h
...
+var formatRe = regexp.MustCompile(`.*\.(.*)$`)
+
 func handleFormattedOutput(writer http.ResponseWriter, request *http.Request, handler func(request *http.Request) (interface{}, error)) {
 	out, err := handler(request)
 	if err != nil {
 		if _, ok := err.(*BadRequestError); ok {
 			http.Error(writer, err.Error(), http.StatusBadRequest)
 			return
 		}
+		if _, ok := err.(*NotFoundError); ok {
```
Comment (ldmonster) [inline pkg/debug/server.go:128]: type switch?

**Review by ldmonster — APPROVED** [review]
